[project]
name = "allie-sdk"
description = "A Python library for the Alation REST APIs."
version = "2.2.3"
readme = "README.md"
requires-python = ">=3.10"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: Apache Software License"
]
keywords = ["Alation", "Allie SDK", "Alation Python SDK", "Alation SDK"]
authors = [
  { name="Mario Aburto", email="mario.aburto@alation.com"},
  { name="Diethard Steiner", email="diethard.steiner@alation.com"},
  { name="Jon Lanham", email="jon.lanham@alation.com"},
  { name="Radek Ignaszewski", email="radek.ignaszewski@alation.com"},
]
maintainers = [
  { name="Mario Aburto", email="mario.aburto@alation.com"},
  { name="Diethard Steiner", email="diethard.steiner@alation.com"},
  { name="Jon Lanham", email="jon.lanham@alation.com"},
  { name="Radek Ignaszewski", email="radek.ignaszewski@alation.com"},
]

dependencies = [
  "requests>=2.32.5",
  "python-json-logger>=4.0.0",
  "python-dateutil>=2.9.0.post0",
]

[dependency-groups]
dev = [
    "deptry>=0.23.1",
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "requests-mock>=1.12.1",
    "ruff>=0.14.3",
]

[project.urls]
Homepage = "https://github.com/Alation/Allie-SDK"
Issues = "https://github.com/Alation/Allie-SDK/issues"
Documentation = "https://alation.github.io/Allie-SDK/"

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
# do not run implicit builds (e.g. when calling uv sync)
package = false

[tool.uv.build-backend]
module-name = "allie_sdk"
module-root = ""

[tool.deptry]
extend_exclude = ["data_source_migration/updateFlag\\.py"]
[tool.ruff]
line-length = 180
indent-width = 4
[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.ruff.lint]
select = [
    "F",   # pyflakes
    "E",   # pycodestyle
    "I",   # isort
    "ANN", # flake8 type annotations
    "RUF", # ruff-specific rules
]
fixable = ["ALL"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
python_version = "3.11"
warn_return_any = true
disallow_untyped_defs = true